### ISSUE TITLE
The published version does not match the config documentation

### ISSUE THREAD

**Issue by yahgwai** [ethereum-ts/deth#83]
The config documentation shows config of the form:

```
blockchain: {
    accounts: {
      privateKeys: [],
      initialBalance: new BN(10000).pow(new BN(18))
    },
    chainId: 420
  },
```

however the latest version 0.0.5, appears to require config of the form:

```
    accounts: {
      privateKeys: [],
      initialBalance: new BN(10000).pow(new BN(18))
    },
   blockchain: {
    chainId: 420
  },
```

**Comment by krzkaczor** [comment]
Hey @yahgwai, yeah that can be right. The project is no longer maintained, I will update the readme with appropriate message. 

If you're looking for something similiar take a look at: https://buidler.dev/buidler-evm/
